'use client';
export const dynamic = 'force-dynamic';
import { useState, useRef, useEffect, useCallback } from 'react';
import { Send, Square, PenLine, Trash2 } from 'lucide-react';
import { cn } from '@/lib/utils';
const PROMPT = '你是AI写作助手，帮助完成写作任务。用中文，提供结构清晰的完整内容。';
const SUGGESTIONS = ['写一篇AI伦理论文大纲','润色这段文字使它更学术化','写封邮件给教授申请延期','写段产品文案介绍学习App'];
export default function WritingPage() {
  const [m,sm]=useState<{id:string;role:'user'|'assistant';content:string}[]>([]);
  const [inp,si]=useState('');const [l,sl]=useState(false);const [s,ss]=useState('');
  const ar=useRef<AbortController|null>(null);const er=useRef<HTMLDivElement>(null);
  useEffect(()=>{er.current?.scrollIntoView({behavior:'smooth'});},[m,s]);
  const stop=useCallback(()=>{ar.current?.abort();sl(false);ss(p=>{if(p)sm(ms=>[...ms,{id:Date.now().toString(),role:'assistant',content:p}]);return'';});},[]);
  const send=useCallback(async(c:string)=>{const um={id:Date.now().toString(),role:'user' as const,content:c};const nm=[...m,um];sm(nm);sl(true);ss('');si('');
    const ctrl=new AbortController();ar.current=ctrl;
    try{const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({model:'deepseek-chat',messages:[{role:'system',content:PROMPT},...nm.map(({role,content})=>({role,content}))]}),signal:ctrl.signal});
    if(!r.ok){const e=await r.json();ss('Error: '+e.error);sl(false);return;};
    const reader=r.body?.getReader();if(!reader){sl(false);return;};const d=new TextDecoder();let ct='';
    while(true){const{done,value}=await reader.read();if(done)break;ct+=d.decode(value,{stream:true});ss(ct);}
    sm(p=>[...p,{id:(Date.now()+1).toString(),role:'assistant',content:ct}]);ss('');}catch(e){if(e instanceof Error&&e.name==='AbortError')return;ss('Network error');}
    finally{sl(false);ar.current=null;}},[m]);
  const disp=[...m];if(s)disp.push({id:'s',role:'assistant' as const,content:s});
  return (<div className="flex flex-col h-[calc(100vh-4rem)]">
    <div className="flex items-center justify-between px-4 py-3 border-b border-custom bg-card"><div className="flex items-center gap-2"><div className="w-7 h-7 rounded-lg bg-gradient-to-br from-blue-500 to-indigo-500 flex items-center justify-center"><PenLine className="w-3.5 h-3.5 text-white"/></div><div><h2 className="text-sm font-semibold text-primary">AI写作助手</h2><p className="text-[10px] text-tertiary">论文、文案、邮件一站式写作</p></div></div>{m.length>0&&<button onClick={()=>{sm([]);ss('');}} className="text-xs text-secondary hover:text-red-500 flex items-center gap-1 px-2 py-1 rounded-lg"><Trash2 className="w-3 h-3"/>清空</button>}</div>
    <div className="flex-1 overflow-y-auto"><div className="max-w-3xl mx-auto px-4">{disp.length===0?(<div className="py-20 text-center"><div className="w-16 h-16 mx-auto rounded-2xl bg-blue-100 dark:bg-blue-900/20 flex items-center justify-center mb-4"><PenLine className="w-8 h-8 text-blue-600"/></div><h3 className="text-lg font-semibold text-primary mb-2">AI 写作助手</h3><p className="text-sm text-secondary mb-6">论文、文案、邮件、报告 一键完成</p><div className="grid grid-cols-2 gap-2 max-w-md mx-auto">{SUGGESTIONS.map(q=>(<button key={q} onClick={()=>send(q)} disabled={l} className="text-xs text-left px-3 py-2.5 rounded-xl glass-card text-secondary hover:text-primary transition-all disabled:opacity-50">{q}</button>))}</div></div>):disp.map(x=>(<div key={x.id} className={cn('flex gap-3 py-4',x.role==='user'?'justify-end':'')}>{x.role!=='user'&&<div className="w-7 h-7 rounded-lg bg-gradient-to-br from-blue-500 to-indigo-500 flex items-center justify-center shrink-0"><PenLine className="w-3.5 h-3.5 text-white"/></div>}<div className={cn('max-w-[80%] rounded-2xl px-4 py-3',x.role==='user'?'bg-blue-600 text-white':'glass-card')}>{x.role==='user'?<p className="text-sm">{x.content}</p>:<div className="chat-content" dangerouslySetInnerHTML={{__html:rW(x.content||'')}}/>}</div>{x.role==='user'&&<div className="w-7 h-7 rounded-lg bg-gray-600 flex items-center justify-center shrink-0"><PenLine className="w-3.5 h-3.5 text-white"/></div>}</div>))}<div ref={er}/></div></div>
    <div className="border-t border-custom bg-card"><div className="max-w-3xl mx-auto px-4 py-3"><div className="flex items-end gap-2 glass-card rounded-2xl px-4 py-2"><textarea value={inp} onChange={e=>si(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();const t=inp.trim();if(t&&!l)send(t);}}} placeholder="描述你的写作需求..." rows={1} className="flex-1 resize-none bg-transparent py-2 text-sm text-primary placeholder:text-tertiary focus:outline-none max-h-[200px]" disabled={l}/>{l?<button onClick={stop} className="w-9 h-9 rounded-lg bg-red-500 text-white flex items-center justify-center shrink-0"><Square className="w-4 h-4" fill="currentColor"/></button>:<button onClick={()=>{const t=inp.trim();if(t)send(t);}} disabled={!inp.trim()} className="w-9 h-9 rounded-lg bg-blue-600 text-white flex items-center justify-center shrink-0 disabled:bg-gray-300"><Send className="w-4 h-4"/></button>}</div><p className="text-center text-[10px] text-tertiary mt-2">AI写作助手</p></div></div>
  </div>);
}
function rW(c:string){let h=c.replace(/```(\w*)\n([\s\S]*?)```/g,(_:string,l:string,code:string)=>`<div class="code-block"><div class="code-header">${l||'code'}</div><pre><code>${code.trim().replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}</code></pre></div>`).replace(/`([^`]+)`/g,'<code class="inline-code">$1</code>').replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>').replace(/^\#{2,3} (.+)$/gm,'<h3>$1</h3>').replace(/^- (.+)$/gm,'<li>$1</li>').replace(/((?:<li>.*<\/li>\n?)+)/g,'<ul>$1</ul>').split(/\n\n+/).map((b:string)=>{b=b.trim();if(!b)return'';if(/^<(h|ul|div|pre)/.test(b))return b;return`<p>${b.replace(/\n/g,'<br/>')}</p>`;}).join('\n');return h;}
